const actionTypes = {
  global: {},

  auth: {
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    LOGOUT_COMPLETED: 'LOGOUT_COMPLETED',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_COMPLETED: 'LOGIN_COMPLETED',
  },
}

export default actionTypes